### ISSUE TITLE
Magento Plain Text Emails not sent as MIME

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-implementation-m2#13]
Just a heads up. This may affect your module.

https://github.com/magento/magento2/pull/23535
https://github.com/magento/magento2/pull/23537

Proposed PR to correct the plain text email MIME problem in Magento 2.2.8+ and 2.3.0+

**Comment by fooman** [comment]
@gwharton Thanks for the heads up (and working on getting emails sorted in M2!)

I have had a quick review of the code changes and believe our module should be okay as is. But will certainly keep an eye on it when it gets merged/released.

**Comment by gwharton** [comment]
Yeah, I seem to remember your module checks if it is plain text, and if it is, then it creates a mime message so that attachments can be added. With this change, you will perhaps need to check on plain text emails if the message is already MIME, and only create the MIME message if it is needed.

All the best.

**Comment by fooman** [comment]
The detection is not on the mime type but rather it was on the absence of a mime part when in text mode (currently we upgrade it to be one). So yes you are absolutely right something  something will not work as expected.

This https://github.com/fooman/emailattachments-implementation-m2/blob/develop/src/Model/MailProcessor.php#L34 will need to get adjusted.  Likely just trying to take the MIME type from the part (or even just removing this line `$htmlPart->type = Mime::TYPE_HTML;` could do the trick).

**Comment by gwharton** [comment]
magento/magento2#23535
magento/magento2#23537

Both now merged into magento. 

Plain text emails generated by Magento are now accidentally adjusted to HTML by the fooman module, as you say, Line 32 of MailProcessor checks if it is a MIME message and sets to HTML. I'll override locally and look forward to an update.

**Comment by fooman** [comment]
@gwharton we have just released [105.1.1](https://github.com/fooman/emailattachments-implementation-m2/compare/v105.1.0...v105.1.1) that incorporates changes to be compatible.

It should also handle scenarios better if the email is already a multipart email when it comes to us. Keen to hear if you ran into any issues - feel free to reopen if you do.

**Comment by fooman** [comment]
Detection of type of email is done by inspecting the first body part as I do not believe this is kept at the message level.

**Comment by gwharton** [comment]
Perfect. Installed and working beautifully.

A couple of niggles on install but not sure the reason, assume something wrong in my local setup and nothing to do with you :)

1. composer refused to update to latest version. If i remove and require again, it reinstalled previous version. If I did composer show fooman......... -l it showed that there was a newer version available but composer update wouldnt grab it. Had to remove and require, explicitly specifying version of latest package.
2. My Email service was reset back to magento builtin instead of my SMTP module after the update.

**Comment by fooman** [comment]
Thanks @gwharton great to hear that does the trick. In terms of the Composer issue it's likely due us not having yet created the release of the metapackage. This should come soon and then make the upgrade smoother via `composer update fooman/*`.

In regards to the smtp module - not sure on that one. There is definitely potential for a conflict with the smtp module. The changes in the last release I however would have thought would not make this better or worse as before.

**Comment by gwharton** [comment]
Yeah, there was no conflict as such. I'm positive it is something I did wrong, just cant remember what!

**Comment by fooman** [comment]
What do you use as smtp module?

**Comment by gwharton** [comment]
Swissup_Email

I've just deployed the update to my live site and that went without a hitch.

**Comment by fooman** [comment]
That's good to hear. Hadn't come across that particular extension so far but please do open a new issue report if there is something for me to look into.
