### ISSUE TITLE
Magento 2.3.3 support

### ISSUE THREAD

**Issue by franckgarnier21** [fooman/emailattachments-implementation-m2#14]
Hello,

For Magento 2.3.3 support.

You need to update the interface from \Magento\Framework\Mail\MessageInterface to \Magento\Framework\Mail\EmailMessageInterface here : Fooman/EmailAttachments/Model/EmailEventDispatcher.php:55
Fooman/EmailAttachments/Model/MailProcessor.php:21
Fooman/EmailAttachments/Model/Api/MailProcessorInterface.php:17

Thanks,

**Comment by fooman** [comment]
@franckgarnier21 Thanks for the heads up - will definitely go through this once 2.3.3 is released for open source. I had hoped that whatever reason they had behind introducing the new interface would have less breakage but seems that is not happening.

**Comment by fooman** [comment]
Adding this here for future reference https://github.com/magento/architecture/pull/144/files

**Comment by franckgarnier21** [comment]
I add this commit reference also : 

The Magento TransportBuilder has changed the factory interface of EmailMessage here : https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php:167

Commit reference: https://github.com/magento/magento2/commit/3a90a0f61e953c8b943b8242525e77477cee8455#diff-dfb3ee5a7f863458afea75f5524cd2e5

I keep you updated when I fix it on my project.

**Comment by franckgarnier21** [comment]
The issue is that we cannot update the message body after his creation. The new interface has only getter or factory.

I'll hack this for my project before your next release.

**Comment by fooman** [comment]
There is this `$this->message = $this->emailMessageInterfaceFactory->create($this->messageData);` which should allow a beforeCreate plugin on `emailMessageInterfaceFactory` to adjust for body content.

**Comment by fooman** [comment]
Closing this one as the latest releases provide 2.3.3 support.
