### ISSUE TITLE
Magento 2.3.2-p2 support

### ISSUE THREAD

**Issue by arnoudhgz** [fooman/emailattachments-implementation-m2#15]
The Magento 2.3.2-p2 Patch is not possible to install due to composer constraint issues.

Are there known issues with the patch and your package?

**Comment by fooman** [comment]
What do you currently have in your composer.json file and from what repository are you trying to install at the moment?

On 2.3.2-p2 Composer does this for me: 
Installs: fooman/emailattachments-implementation-m2:105.1.1, fooman/emailattachments-m2:3.1.10

**Comment by fooman** [comment]
Ideally you would have `fooman/emailattachments-m2:^3.0` in your composer.json file. It then doesn't matter what version of Magento you are trying to install. During the `composer update` command the correct version will get pulled in by Composer.

**Comment by arnoudhgz** [comment]
@fooman thanks for the reply, it seems to work now with `fooman/emailattachments-m2:^3.0`. This morning when I just tried updating Magento it failed. But after removing fooman from composer and do a new require it seemed to work.
