### ISSUE TITLE
Feature request / question: Attach any PDF to an order

### ISSUE THREAD

**Issue by amenk** [fooman/emailattachments-implementation-m2#18]
Would it be in scope of the module to allow to attach any fixed PDF to an order or should that be done in an own module?

**Comment by fooman** [comment]
@amenk thanks for the inquiry. We have built such a module inhouse already so would indeed consider it out of scope for this extension.

**Comment by amenk** [comment]
Thanks. Did you base it on top of this extension?

**Comment by fooman** [comment]
@amenk indeed that's what we did. We have some further plans for it but if you are only looking to attach up to 2 pdf files happy to sell it to you https://store.fooman.co.nz/magento-extension-attachment-manager-m2.html.

**Comment by amenk** [comment]
Oh, interesting, we already had/have plans to do this as a FOSS extension. Hope that's okay :) We'll see.
