### ISSUE TITLE
Ability to check out of github directly into Magento tree

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-implementation-m2#2]
Alot of people use git subtree to add third party modules into their own Magento store's github tree.

This module does not work if you do that.

The module is not recognised because there is no registration.php in the project root.

Even when you do add a registration file, compilation fails due to classpath issues. Presumably the autoload stuff is not working properly with DI compilation.

Consider restructuring module along the Magento guidelines, or make necessary changes to project root to allow module to be run with the following structure/location

app/code/Fooman/EmailAttachments/src/.....

**Comment by fooman** [comment]
@gwharton thanks for the suggestion. Installation under app/code is not something that I want to support (I am of the firm view that everything should be installed via Composer).

**Comment by gwharton** [comment]
Sure. No problems.
