### ISSUE TITLE
Magento 2.4 and PHP 7.4 support

### ISSUE THREAD

**Issue by pikulsky** [fooman/emailattachments-implementation-m2#20]
Could you please update the modules to work in Magento 2.4 ?

I've added PR for "magento2-phpunit-bridge" module, see https://github.com/fooman/magento2-phpunit-bridge/pull/1

Also, I've updated composer.json files for "emailattachments-implementation-m2" and "emailattachments-m2":
- https://github.com/pikulsky/emailattachments-m2/tree/feature/support-magento-2.4
- https://github.com/pikulsky/emailattachments-implementation-m2/tree/feature/support-magento-2.4
I guess I would need to create a PR for some branch in your repositories (not master, maybe develop or some another), what do you think?

**Comment by fooman** [comment]
@pikulsky thanks for letting us know. There was an issue in the script that was supposed to push this to github but it should now also be on here.

**Comment by pikulsky** [comment]
@fooman , yes, indeed, now support for PHP 7.4 and Magento 2.4 is here. Thanks a lot!
