### ISSUE TITLE
In my site one feature is automatically mail sending but when I am using mail attachment extension my automatic invoice mail are stuck I need to send attachment with automatic mail sending functionality 

### ISSUE THREAD

**Issue by rajudiya** [fooman/emailattachments-implementation-m2#22]

**Comment by fooman** [comment]
Please provide additional information and steps for us to be able to replicate the issue using a Magento vanilla install.

Include any error messages from your logs that you seem relevant.

I'll close the issue for now. Please re-open with the above info.

**Comment by rajudiya** [comment]
No any logs and error in the log only issue in automatically email sending process

**Comment by fooman** [comment]
Sorry with this little info we unfortunately can't help you from afar. If you would like to hire us to investigate this directly we are open to do so. If you would like to proceed with this please get back in touch via our support email.
