### ISSUE TITLE
105.0.1 fails di compilation

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-implementation-m2#4]
Magento 2.2.7
PHP 7.1.24-1+ubuntu18.10.1+deb.sury.org+1

php bin/magento setup:di:compile results in

PHP Fatal error:  A void function must not return a value in /xxxxxxxxxxx/generated/code/Fooman/EmailAttachments/Observer/AbstractSendShipmentObserver/Interceptor.php on line 24

**Comment by gwharton** [comment]
Also fails when sending messages

 PHP Fatal error:  A void function must not return a value in /home/developer/dev.lubefinder.com.html/generated/code/Fooman/EmailAttachments/Observer/BeforeSendInvoiceObserver/Interceptor.php on line 37'

 PHP Fatal error:  A void function must not return a value in /home/developer/dev.lubefinder.com.html/generated/code/Fooman/EmailAttachments/Observer/BeforeSendInvoiceObserver/Interceptor.php on line 50'

**Comment by fooman** [comment]
@gwharton thanks for the reports. It looks like you installed version 105.0.1 into Magento 2.2.7. That should not be possible when using Composer due to the version constraints, ie magento/framework 102. Can you please confirm how you ended up with this version combination so that we can take a look.

**Comment by gwharton** [comment]
Ahh, my bad. I dont use composer. I just downloaded the zip and uploaded it to my dev store to check it out.

**Comment by gwharton** [comment]
If 105 release is for 2.3 only, then please close these issues. I have reverted back to 104.

**Comment by fooman** [comment]
I suggest to give Composer a try as otherwise it would be a nightmare to get all the right packages aligned. 105 is for Magento 2.3 only as Magento made changes to the Zend Framework packages in use.

**Comment by gwharton** [comment]
No worries. I just picked up the non magento dependencies from the modules composer.json and reflected the requirement in my top level composer.json file and composer updated to get the dependencies.

I'll relook at composer for module installation when I shift up to 2.3 in a few months time. Cheers for the work though, and sorry for the waste of your time.
