### ISSUE TITLE
105.0.1 Fails to send message

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-implementation-m2#5]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Fooman\\EmailAttachments\\Model\\MailProcessor::createMultipartMessage() must be an instance of Magento\\Framework\\Mail\\MailMessageInterface, instance of Magento\\Framework\\Mail\\Message given, called in /home/developer/dev.lubefinder.com.html/app/code/Fooman/EmailAttachments/Model/EmailEventDispatcher.php on line 82 and defined in /home/developer/dev.lubefinder.com.html/app/code/Fooman/EmailAttachments/Model/MailProcessor.php:21\nStack trace:\n#0 /home/developer/dev.lubefinder.com.html/app/code/Fooman/EmailAttachments/Model/EmailEventDispatcher.php(82): Fooman\\EmailAttachments\\Model\\MailProcessor->createMultipartMessage(Object(Magento\\Framework\\Mail\\Message), Object(Fooman\\EmailAttachments\\Model\\AttachmentContainer))

I believe Line 18 of /Model/Api/MailProcessorInterface.php should be
        \Magento\Framework\Mail\MessageInterface $message,
and line 22 of /Model/MailProcessor.php
        \Magento\Framework\Mail\MessageInterface $message,

**Comment by fooman** [comment]
related to #4
