### ISSUE TITLE
105.0.1 txt based emails fail to send

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-implementation-m2#6]
Not sure if it is a side effect of having UTF characters in the subject, but my store emails are text based and no longer send with 105.0.1

In function createMultipartMessage

The code $textPart = new MimePart($existingEmailBody); fails as $existingEmailBody is already a \Zend\Mime\Part

Fails with exception "Content must be string or resource; received "Zend_Mime_Part""

![image](https://user-images.githubusercontent.com/30697781/49701527-7b543980-fbe5-11e8-9d0d-f88f4ec213c3.png)

**Comment by gwharton** [comment]
For some reason, we got a zend_mime_part object, presumably from zendframework 1????

Got past that with new else if inside createMultipleMessage to convert to zend framework 2 Zend\Mime\Part and add to message

`            } else if (\is_object($existingEmailBody) && $existingEmailBody instanceof \Zend_Mime_Part) {
                $textPart = new MimePart($existingEmailBody->getRawContent());
                $textPart->type = Mime::TYPE_TEXT;
                $textPart->charset = 'utf-8';
                $textPart->encoding = Mime::ENCODING_QUOTEDPRINTABLE;
                $body->addPart($textPart);
`

Now getting 

`"Recoverable Error: Object of class Zend\Mime\Message could not be converted to string in /vendor/magento/zendframework1/library/Zend/Mime.php on line 469"`

Looks like I'm getting some sort of conflict between zend framework 1 and 2 since installing zendframework/zend-mime 2.7.1 for this module. Not sure what the heck is going on!

**Comment by fooman** [comment]
related to #4
