### ISSUE TITLE
Order confirmation email is not sent in Magento 2.2.5

### ISSUE THREAD

**Issue by jahicDario** [fooman/emailattachments-implementation-m2#7]
In clean install of Magento 2.2.5, mail for order confirmation is not sent. Mail settings is correct and mail is sending when user send it directly from admin but sending automatically when customer finish order is working only when pdf attachment is turned off.

**Comment by fooman** [comment]
Can you please confirm which version of the extensions are installed. The output of `composer show fooman/*` would be great.

Also can you please screenshot the setting that you are changing that is the difference between it sending and not.

And lastly anything in the log files or any other extensions installed that change the emailing process?

**Comment by jahicDario** [comment]
I am using next versions: 
Fooman_PrintOrderPdf 2.1.0
Fooman_EmailAttachments 2.0.8

I am getting next error, when i enter debugger:
**Invalid template file:'Magento_OfflinePayments::info/pdf/checkmo.phtml' in module: 'Magento_OfflinePayments' block's name: 'info\checkmo_0'**
This is happening in Fooman\PrintOrderPdf\Model\Pdf\Order:44
```
$this->insertOrder(
                $page,
                $order,
                $this->_scopeConfig->isSetFlag(
                    self::XML_PATH_SALES_PDF_INVOICE_PUT_ORDER_ID,
                    \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
                    $order->getStoreId()
                )
            );
```

My guess is that Plugin that should change the template file in toPdf() method is not working. 

If I turned off _Attach Order as PDF_ in Sales->Sales Email->Order, email is sent but without pdf. 

As I mention before, sending email with attached pdf is working from admin, this is case in frontend after creating order.

**Comment by fooman** [comment]
Please update to more recent versions: 
3.0.4 for Fooman_EmailAttachments
and
3.1.0 for Fooman_PrintOrderPdf

Please re-open if that doesn't address the issue.

**Comment by jahicDario** [comment]
I replace modules with latest version, now I can not place order at all. In clean version of Magento 2.2.5 when pdf attachment is turned on, I get just empty error.
![fooman-email-attachment](https://user-images.githubusercontent.com/17848628/50958557-4d526580-14c1-11e9-8bdb-2b9dd9810651.jpg)

**Comment by fooman** [comment]
@jahicDario when you say latest versions which versions are that?

If you are using Chrome you should be able to open the developer tools and see in the network tab some more info on this.

**Comment by jahicDario** [comment]
Setup version of modules are the same, but files are changed, so I am not really sure which version is this, but I downloaded yesterday from your website:
![selection_018](https://user-images.githubusercontent.com/17848628/50959674-c783e980-14c3-11e9-8103-0d104a6d80e4.jpg)

I also check the console and the logs in var folder but there is no information about error.

**Comment by fooman** [comment]
Setup versions only indicate the version of the database. Please review the composer.json files - or better yet the output of `composer show fooman/*` to confirm extension version numbers.

**Comment by jahicDario** [comment]
Versions: 
EmailAttachments: 105.0.2
PrintOrderPdf: 103.1.0

`
{
    "name": "fooman/printorderpdf-implementation-m2",
    "description": "Print the order as a pdf from the admin",
    "type": "magento2-module",
    "license": "OSL-3.0",
    "version": "103.1.0",
    "autoload": {
        "psr-4": {
            "Fooman\\PrintOrderPdf\\": ""
        },
        "files": [
            "registration.php"
        ]
    },
    "require": {
        "php": "~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0",
        "magento/framework": "^100.0 | ^101.0.0 | ^102.0.0",
        "magento/module-backend": "^100.1.0 | ^101.0.0",
        "magento/module-sales": "^100.1.0 | ^101.0.0 | ^102.0.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

`
{
    "name": "fooman/emailattachments-implementation-m2",
    "license": "OSL-3.0",
    "description": "Automatically attach pdf and terms and conditions documents to outgoing sales emails.",
    "type": "magento2-module",
    "version": "105.0.2",
    "autoload": {
        "psr-4": {
            "Fooman\\EmailAttachments\\": ""
        },
        "files": [
            "registration.php"
        ]
    },
    "require": {
        "php": "~7.1.3||~7.2.0",
        "magento/framework": "^102.0.0",
        "magento/module-backend": "^101.0.0",
        "magento/module-sales": "^102.0.0",
        "magento/module-checkout-agreements": "^100.0.2",
        "magento/module-email": "^101.0.0",
        "zendframework/zend-mime": "^2.5"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "suggest": {
        "fooman/printorderpdf-m2": "Allows attaching the order confirmation pdf to the order confirmation email",
        "fooman/pdfcustomiser-m2": "Allows to easily customise the sales pdfs while also reducing file sizes "
    }
}
`

**Comment by fooman** [comment]
Are you using composer to install the extension? Version 105.0.2 of EmailAttachments Implementation is for Magento 2.3 only.

**Comment by jahicDario** [comment]
I got it working, problem was the version of modules, for Magento 2.2.5 the correct combination of modules are: 
PrintOrderPdf: 103.1.0
EmailAttachments: 104.0.3

Thank you for your help! :)
