### ISSUE TITLE
Shipment PDF attachment is not added when using copy method Seperate Email

### ISSUE THREAD

**Issue by peterjaap** [fooman/emailattachments-implementation-m2#9]
(only seen with Shipment PDF but possibly an issue for other email types as well)

We had this configuration;

![image](https://user-images.githubusercontent.com/431360/52473123-548a9300-2b95-11e9-9ee1-80d33e26fc4f.png)

This caused the shipment PDF to **not** be attached to the copied email. When we set it to this;

![image](https://user-images.githubusercontent.com/431360/52473111-4b99c180-2b95-11e9-9b3f-80f586d1c5af.png)

The PDF **is** attached to the bcc'ed email. Something's up there..

**Comment by fooman** [comment]
Hey @peterjaap do you mind confirming which versions you have currently installed (output of `composer show fooman/*` would be great. Also are there any other emailing extensions present? And lastly are you currently using the async email sending modus, ie via cron?

**Comment by peterjaap** [comment]
```
$ composer show "fooman/*"
fooman/emailattachments-m2 2.1.0    Automatically attach pdf and terms and conditions documents to outgoing sales emails.
fooman/pdfcore-m2          9.6.6    Common functionality for all Fooman Pdf extensions
fooman/pdfcustomiser-m2    7.2.3    Customise your sales pdf
fooman/printorderpdf-m2    2.2.2    Print the order as a pdf from the admin
fooman/tcpdf               6.2.25.2 Trimmed down version of TCPDF (no examples, tools and minimal fonts). TCPDF is a PHP class for generating PDF documents and barcodes.
```

```
$ composer show "*mail*"
dotmailer/dotmailer-magento2-extension 2.4.9   dotmailer integration for magento 2
ebizmarts/mailchimp-lib                3.0.22  API client library for the MailChimp
fooman/emailattachments-m2             2.1.0   Automatically attach pdf and terms and conditions documents to outgoing sales emails.
magento/module-email                   100.2.1 N/A
mailchimp/mc-magento2                  1.0.29  Connect MailChimp with Magento
```

```
$ magerun2 config:show sales_email/general/async_sending
Configuration for path: "sales_email/general/async_sending" doesn't exist
```

So it is set to its default value, which is disabled.

**Comment by fooman** [comment]
Hey @peterjaap seeing that you are also using our PdfCustomiser extension I suggest moving this to our support helpdesk (support@fooman.co.nz). 

The email attachments version currently installed is not on the latest version and I believe upgrading you would fix this particular issue. If you are still within the upgrade period and you are using our hosted repo :
```
composer require fooman/pdfcustomiser-m2:^8.0 --no-update
composer update fooman/*
```
should do the trick.
